[pytest]
testpaths = tests
asyncio_mode = auto
pythonpath = .. .
addopts =
    --cov=.
    --cov-report=xml:coverage.xml
    --cov-report=term-missing
    --cov-fail-under=83
    -v
filterwarnings =
    ignore::DeprecationWarning
    ignore::pytest.PytestUnraisableExceptionWarning
